import type { Driver, Clinic } from './types';

// By storing the data in a 'db' object and exporting that,
// we can simulate a database in memory.
// Node.js will cache this module, so the 'db' object will persist
// across server requests in development.

const db = {
  drivers: [
    {
      id: 'DRI001',
      name: 'Carlos Villa',
      status: 'in-trip' as const,
      location: { lat: -12.04, lng: -77.03 },
      vehicle: 'Toyota Prius',
      rating: 4.8,
      tripsToday: 5,
      dni: '12345678',
      dob: new Date('1985-05-15'),
      phone1: '987654321',
      address: 'Av. Falsa 123',
      district: 'Miraflores',
      email: 'carlos.villa@example.com',
      licenseNumber: 'Q12345678',
      carBrand: 'Toyota',
      carModel: 'Prius',
      plateNumber: 'A1B-234',
      hireDate: new Date('2022-01-15'),
    },
    {
      id: 'DRI002',
      name: 'Ana Torres',
      status: 'available' as const,
      location: { lat: -12.05, lng: -77.045 },
      vehicle: 'Hyundai Elantra',
      rating: 4.9,
      tripsToday: 7,
      dni: '87654321',
      dob: new Date('1990-08-20'),
      phone1: '912345678',
      address: 'Calle Verdadera 456',
      district: 'San Isidro',
      email: 'ana.torres@example.com',
      licenseNumber: 'R87654321',
      carBrand: 'Hyundai',
      carModel: 'Elantra',
      plateNumber: 'C2D-567',
      hireDate: new Date('2021-11-30'),
    },
    {
      id: 'DRI003',
      name: 'Luis Ramos',
      status: 'in-trip' as const,
      location: { lat: -12.06, lng: -77.025 },
      vehicle: 'Kia Rio',
      rating: 4.7,
      tripsToday: 4,
      dni: '11223344',
      dob: new Date('1988-12-01'),
      phone1: '998877665',
      address: 'Jirón de la Unión 789',
      district: 'Lima',
      email: 'luis.ramos@example.com',
      licenseNumber: 'T11223344',
      carBrand: 'Kia',
      carModel: 'Rio',
      plateNumber: 'E3F-890',
      hireDate: new Date('2023-03-10'),
    },
    {
      id: 'DRI004',
      name: 'Sofia Paz',
      status: 'offline' as const,
      location: { lat: -12.03, lng: -77.05 },
      vehicle: 'Nissan Versa',
      rating: 4.9,
      tripsToday: 0,
       dni: '44332211',
      dob: new Date('1995-02-25'),
      phone1: '955667788',
      address: 'Av. Arequipa 1011',
      district: 'Lince',
      email: 'sofia.paz@example.com',
      licenseNumber: 'V44332211',
      carBrand: 'Nissan',
      carModel: 'Versa',
      plateNumber: 'G4H-112',
      hireDate: new Date('2023-08-01'),
    },
    {
      id: 'DRI005',
      name: 'Jorge Luna',
      status: 'available' as const,
      location: { lat: -12.07, lng: -77.06 },
      vehicle: 'Toyota Yaris',
      rating: 5.0,
      tripsToday: 6,
       dni: '55667788',
      dob: new Date('1992-07-30'),
      phone1: '933445566',
      address: 'Av. Benavides 1213',
      district: 'Miraflores',
      email: 'jorge.luna@example.com',
      licenseNumber: 'W55667788',
      carBrand: 'Toyota',
      carModel: 'Yaris',
      plateNumber: 'I5J-314',
      hireDate: new Date('2020-05-20'),
    },
    {
      id: 'DRI006',
      name: 'Maria Flores',
      status: 'available' as const,
      location: { lat: -12.08, lng: -77.01 },
      vehicle: 'Chevrolet Onix',
      rating: 4.6,
      tripsToday: 3,
       dni: '88776655',
      dob: new Date('1998-10-05'),
      phone1: '911223344',
      address: 'Av. La Marina 1415',
      district: 'San Miguel',
      email: 'maria.flores@example.com',
      licenseNumber: 'X88776655',
      carBrand: 'Chevrolet',
      carModel: 'Onix',
      plateNumber: 'K6L-516',
      hireDate: new Date('2024-01-05'),
    },
  ],
  clinics: [
    {
      id: 'CLI001',
      name: 'SANNA',
      address: 'Av. El Polo 23, Surco',
      centralPhone: '01-610-7300',
      clinicEmail: 'contacto@sanna.pe',
      contactName1: 'Juan Perez',
      charge1: 'Jefe de Operaciones',
      cellphone1: '987654321',
      emailCli1: 'jperez@sanna.pe',
      serviceTypes: 'MAD, Laboratorio',
    },
    {
      id: 'CLI002',
      name: 'Clínica Internacional',
      address: 'Jr. Washington 1471, Cercado de Lima',
      centralPhone: '01-330-0300',
      clinicEmail: 'info@cinternacional.com.pe',
      contactName1: 'Maria Rodriguez',
      charge1: 'Coordinadora de Traslados',
      cellphone1: '912345678',
      emailCli1: 'mrodriguez@cinternacional.com.pe',
      serviceTypes: 'MAD-CI, CI',
    },
    {
      id: 'CLI003',
      name: 'Clínica San Borja',
      address: 'Av. Guardia Civil 333, San Borja',
      centralPhone: '01-211-1000',
      clinicEmail: 'atencion@csb.com.pe',
      serviceTypes: 'TDP CEG/GSB, RDM',
    },
    {
      id: 'CLI004',
      name: 'JP',
      address: 'Av. Javier Prado Este 1066, San Isidro',
      clinicEmail: 'servicios@jp.pe',
      serviceTypes: 'JP',
    },
    {
      id: 'CLI005',
      name: 'SM',
      address: 'Av. Sucre 155, Pueblo Libre',
      serviceTypes: 'SM, MEDICINA',
    }
  ]
};

export const drivers: Driver[] = db.drivers;
export const clinics: Clinic[] = db.clinics;
